all: messageQueue future observer

messageQueue: messageQueue.cpp
	g++ -Wall -lpthread -std=c++11 messageQueue.cpp -o messageQueue

future: future.cpp
	g++ -Wall -lpthread -std=c++11 future.cpp -o future

observer: observer.cpp
	g++ -Wall -lpthread -std=c++11 observer.cpp -o observer
