all: dynamicDecorator mixinDecorator composite

dynamicDecorator: dynamicDecorator.cpp
	g++ -Wall -std=c++11 dynamicDecorator.cpp -o dynamicDecorator


mixinDecorator: mixinDecorator.cpp
	g++ -Wall -std=c++11 mixinDecorator.cpp -o mixinDecorator

composite: composite.cpp
	g++ -Wall -std=c++11 composite.cpp -o composite
