all: dynamicDecorator mixinDecorator

dynamicDecorator: dynamicDecorator.cpp
	g++ -Wall -std=c++11 dynamicDecorator.cpp -o dynamicDecorator


mixinDecorator: mixinDecorator.cpp
	g++ -Wall -std=c++11 mixinDecorator.cpp -o mixinDecorator
